### ISSUE TITLE
incorrect handling of repeated letters in guess word

### ISSUE THREAD

**Issue by zhussaini** [daneofmanythings/wohrdle#1]
![wohrdle-bug](https://github.com/daneofmanythings/wohrdle/assets/11390757/35ad6d31-3f76-43a4-93f0-0bcc19fbbf63)

My third guess had two S's in it. One was highlighted yellow and one green. This made me think that the word had two S's in it, but that was not the case.

![wohrdle-bug-2](https://github.com/daneofmanythings/wohrdle/assets/11390757/9151eaa1-8f4a-49e3-8b74-9cee6e4d6373)

The additional S in LUSTS shouldn't have been highlighted yellow.

**Comment by daneofmanythings** [comment]
This issue should now be resolved as of this commit: https://github.com/daneofmanythings/wohrdle/commit/54bdfbf3d37dd298127428ea57eaa9107acc0220
